CREATE TABLE room_member (
    userId BINARY(16),
    roomId BINARY(16),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    joinedAt DATETIME,
    leavedAt DATETIME
);