version: '3.8'
services:
  mysql:
    platform: linux/amd64
    image: 'mysql:5.7'
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: ''
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql