version: '3.8'
services:
  mysql:
    platform: linux/amd64
    image: 'mysql:5.7'
    restart: always
    environment:
      MYSQL_DATABASE: chat
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306:3306
    volumes:
      - volume-db:/var/lib/mysql

volumes:
  volume-db: